# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.5.0'

gem 'activepesel', '~> 0.1.1'
gem 'bootsnap', '~> 1.2.0'
gem 'bootstrap', '~> 4.0.0'
gem 'coffee-rails', '~> 4.2.2'
gem 'kaminari', '~> 1.1.1'
gem 'puma', '~> 3.11.3'
gem 'rails', '~> 5.2.0.rc1'
gem 'sass-rails', '~> 5.0.7'
gem 'turbolinks', '~> 5.1.0'
gem 'uglifier', '~> 4.1.8'

group :development, :test do
  gem 'byebug', platforms: %i[mri mingw x64_mingw]
  gem 'sqlite3'
end

group :production do
  gem 'pg', '~> 1.0.0'
end

group :development do
  gem 'listen', '~> 3.1.5'
  gem 'spring', '~> 2.0.2'
  gem 'spring-watcher-listen', '~> 2.0.1'
  gem 'web-console', '~> 3.5.1'
end

group :test do
  gem 'capybara', '~> 2.18.0'
  gem 'chromedriver-helper', '~> 1.2.0'
  gem 'selenium-webdriver', '~> 3.11.0'
end

gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]
